spring.application.name=movie-info-service
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=moviesdb

eureka.client.enabled=true

apikey=b0af84324ea41ca39f4311c9156e94e3
spring.main.allow-bean-definition-overriding=true