spring.application.name=movie-catalog-service
server.port=8081
management.endpoints.web.exposure.include=hystrix.stream
grpc.client.trending-service.address=static://localhost:9092
grpc.client.trending-service.negotiationType=plaintext
spring.main.allow-bean-definition-overriding=true
apikey=b0af84324ea41ca39f4311c9156e94e3